In [5]:
import pandas as pd
df = pd.read_json("data/ergast-results.json")

In [9]:
df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'code', 'forename',
       'surname', 'dob', 'nationality', 'driverUrl', 'year', 'round', 'date',
       'quali_date', 'quali_time', 'location', 'country', 'gp', 'status',
       'constructor', 'constructorNationality', 'constructorRef', 'name'],
      dtype='object')

In [33]:
first_wins = df[df['position'] == 1].sort_values(by=["date"])[['date','constructor']].drop_duplicates(subset=['constructor'],keep='first')
first_wins

            date      constructor
18565 1950-05-13       Alfa Romeo
22078 1950-05-30     Kurtis Kraft
5908  1951-07-14          Ferrari
22241 1952-05-30            Kuzma
21524 1953-09-13         Maserati
22766 1954-07-04         Mercedes
21944 1956-05-30           Watson
21969 1957-05-30          Epperly
22477 1957-07-20          Vanwall
21227 1958-01-19           Cooper
24024 1959-05-10    Cooper-Climax
20460 1959-05-31              BRM
15295 1960-05-29       Team Lotus
24284 1961-05-14     Lotus-Climax
21376 1962-07-08          Porsche
24860 1964-06-28   Brabham-Climax
9111  1965-10-24            Honda
25087 1966-07-03    Brabham-Repco
24497 1966-10-02        Lotus-BRM
23851 1966-10-23  Cooper-Maserati
24648 1967-06-04       Lotus-Ford
25051 1967-06-18    Eagle-Weslake
24962 1968-06-09     McLaren-Ford
25197 1968-06-23       Matra-Ford
24795 1969-08-03     Brabham-Ford
16322 1970-03-07          Brabham
17095 1970-04-19            March
13244 1971-04-18          Tyrrell
640   1972-03-04          McLaren
20277 1975-06-22          Hesketh
20945 1976-08-15           Penske
19906 1977-01-09             Wolf
14225 1977-06-19           Ligier
19692 1977-08-14           Shadow
3969  1979-07-01          Renault
2561  1979-07-14         Williams
12649 1986-10-12         Benetton
10411 1998-08-30           Jordan
13026 1999-09-26          Stewart
1956  2008-06-08       BMW Sauber
4546  2008-09-14       Toro Rosso
12983 2009-03-29            Brawn
7861  2009-04-19         Red Bull
25705 2012-11-04         Lotus F1
26373 2020-09-06       AlphaTauri
26323 2020-12-06     Racing Point
26543 2021-08-01   Alpine F1 Team

In [17]:
import polars as pl
import altair as alt

In [71]:
fw_pl = pl.from_pandas(first_wins).group_by_dynamic(index_column="date", every="1y").agg(pl.col("constructor").unique().len())
fw_pl

shape: (33, 2)
┌─────────────────────┬─────────────┐
│ date                ┆ constructor │
│ ---                 ┆ ---         │
│ datetime[ns]        ┆ u32         │
╞═════════════════════╪═════════════╡
│ 1950-01-01 00:00:00 ┆ 2           │
│ 1951-01-01 00:00:00 ┆ 1           │
│ 1952-01-01 00:00:00 ┆ 1           │
│ 1953-01-01 00:00:00 ┆ 1           │
│ 1954-01-01 00:00:00 ┆ 1           │
│ …                   ┆ …           │
│ 2008-01-01 00:00:00 ┆ 2           │
│ 2009-01-01 00:00:00 ┆ 2           │
│ 2012-01-01 00:00:00 ┆ 1           │
│ 2020-01-01 00:00:00 ┆ 2           │
│ 2021-01-01 00:00:00 ┆ 1           │
└─────────────────────┴─────────────┘

In [107]:
alt.Chart(pd.DataFrame([{"a":1,"b":2}])).mark_bar().encode(alt.X("a:T"),alt.Y("b:Q"))

alt.Chart(...)

In [95]:
alt.renderers.enable('notebook')

ValueError:
To use the 'notebook' renderer, you must install the vega package
and the associated Jupyter extension.
See https://altair-viz.github.io/getting_started/installation.html
for more information.

In [125]:
fw_pl.to_pandas()

         date  constructor
0  1950-01-01            2
1  1951-01-01            1
2  1952-01-01            1
3  1953-01-01            1
4  1954-01-01            1
5  1956-01-01            1
6  1957-01-01            2
7  1958-01-01            1
8  1959-01-01            2
9  1960-01-01            1
10 1961-01-01            1
11 1962-01-01            1
12 1964-01-01            1
13 1965-01-01            1
14 1966-01-01            3
15 1967-01-01            2
16 1968-01-01            2
17 1969-01-01            1
18 1970-01-01            2
19 1971-01-01            1
20 1972-01-01            1
21 1975-01-01            1
22 1976-01-01            1
23 1977-01-01            3
24 1979-01-01            2
25 1986-01-01            1
26 1998-01-01            1
27 1999-01-01            1
28 2008-01-01            2
29 2009-01-01            2
30 2012-01-01            1
31 2020-01-01            2
32 2021-01-01            1

In [153]:
alt.Chart(
    fw_pl.to_pandas()
).mark_bar(
).encode(
    alt.X("date:T"),
    alt.Y("constructor:Q")
)

alt.Chart(...)

In [61]:
pl.from_pandas(first_wins).group_by_dynamic(index_column="date", every="1y").agg(pl.col("constructor").unique().len()).to_pandas()

         date  constructor
0  1950-01-01            2
1  1951-01-01            1
2  1952-01-01            1
3  1953-01-01            1
4  1954-01-01            1
5  1956-01-01            1
6  1957-01-01            2
7  1958-01-01            1
8  1959-01-01            2
9  1960-01-01            1
10 1961-01-01            1
11 1962-01-01            1
12 1964-01-01            1
13 1965-01-01            1
14 1966-01-01            3
15 1967-01-01            2
16 1968-01-01            2
17 1969-01-01            1
18 1970-01-01            2
19 1971-01-01            1
20 1972-01-01            1
21 1975-01-01            1
22 1976-01-01            1
23 1977-01-01            3
24 1979-01-01            2
25 1986-01-01            1
26 1998-01-01            1
27 1999-01-01            1
28 2008-01-01            2
29 2009-01-01            2
30 2012-01-01            1
31 2020-01-01            2
32 2021-01-01            1